### ISSUE TITLE
NativeEdit invisible on Unity 5.6

### ISSUE THREAD

**Issue by nicolasform** [YousicianGit/UnityNativeEdit#34] opened 2017-05-18 00:20 UTC
Hello guys,
I'm having some issues on Android since the update to Unity 5.6: the native field does not appear like before (for example the cursor has disappeared) and it is much slower.
I tried to use Android SDK 23, 24 and 25 and I got the same result. I hope I will not have to revert to Unity 5.5...
Does anybody is experiencing the same thing? Any idea?
Cheers,
Nicolas

EDIT: I'm using Unity Editor 5.6.1f1 on Windows 10, and my the Android version on my device is 6.0.1. See further for a screenshot on a fresh project.

**Comment by vnorilo** [comment] 2017-05-18 06:09
Which version of Unity 5.6 are you using? We had a problem with the text and cursor not showing, but as of 5.6.1 the plugin seems to work as before.

**Comment by nicolasform** [comment] 2017-05-18 13:33
Thanks for your answer @vnorilo . I updated from 5.5.1 to 5.6.1f1 and I did not updated UnityNativeEdit since February. I made many changes to the code so I'm a bit reluctant to update directly from your Git, it will be a mess to merge. Can you point me what changes exactly has been made to fix the view hierarchy issue please? As I understood this was the problem to the text and cursor not showing, right?

**Comment by nicolasform** [comment] 2017-05-18 21:30
Ok, now it's getting stranger. I created a new project and add to it the most recent sources from the master branch. Then I tried to run the demo: no text and no cursor appear. When I click on the text box, the keyboard appear and when I type I see in the log that the app get that I am typing, but nothing appears inside the text box. I really don't get why it is happening. Any idea?

I'm using Unity Editor 5.6.1f1 on Windows 10, and my the Android version on my device is 6.0.1.

![screenshot_2017-05-18-23-25-30](https://cloud.githubusercontent.com/assets/8779897/26224171/8139f64e-3c21-11e7-8448-28ffa5da170d.png)

**Comment by Hemaolle** [comment] 2017-05-24 12:41
Some info about native input being invisible in Unity 5.6:
https://forum.unity3d.com/threads/android-input-in-fragment-invisible-but-still-interactable-after-update-to-unity-5-6-1.471426/.

I'm working on a fix now.

**Comment by nicolasform** [comment] 2017-05-24 12:49
Thx @Hemaolle, I'm investigating also on my side since few hours. Let's get in touch about it.

**Comment by nicolasform** [comment] 2017-05-24 15:33
I have a fix: in the android project you should add two classes:

**UnityPlayerNotOnTop.java**
```
package com.bkmin.android;

import com.unity3d.player.*;
import android.content.ContextWrapper;
import android.view.SurfaceView;
import android.view.View;

public class UnityPlayerNotOnTop
        extends UnityPlayer
{
    public UnityPlayerNotOnTop(ContextWrapper contextwrapper) {
        super(contextwrapper);
    }

    public void addView(View child) {
        if (child instanceof SurfaceView) {
            ((SurfaceView)child).setZOrderOnTop(false);
        }
        super.addView(child);
    }
}
```

**UnityPlayerNotOnTopActivity.java**
```
package com.bkmin.android;

import com.unity3d.player.*;
import android.os.Bundle;

public class UnityPlayerNotOnTopActivity
        extends UnityPlayerActivity
{
    @Override
    public void onCreate(Bundle bundle) {
        requestWindowFeature(1);
        super.onCreate(bundle);
        getWindow().setFormat(2);
        mUnityPlayer = new UnityPlayerNotOnTop(this);
        setContentView(mUnityPlayer);
        mUnityPlayer.requestFocus();
    }
}
```

In your **Android manifest**, change the activity line to:
```
<activity android:name="com.bkmin.android.UnityPlayerNotOnTopActivity"
                  android:label="@string/app_name">
```

It is not the best solution, we should avoid to override the UnityPlayerActivity, but it works.

**Comment by Hemaolle** [comment] 2017-05-26 06:58
Thanks a lot @nicolasform. Maybe you could fork the repository and make a pull request with that fix?

**Comment by Hemaolle** [comment] 2017-05-26 10:11
Never mind @nicolasform, I'll make a branch for this repository.

**Comment by nicolasform** [comment] 2017-05-26 10:18
Just seen your comment @Hemaolle. Ok thanks for the branch :)

**Comment by Hemaolle** [comment] 2017-05-26 10:39
It should be fixed here: https://github.com/YousicianGit/UnityNativeEdit/tree/fix/unity5.6.

**Comment by Hemaolle** [comment] 2017-05-26 10:42
And of course if you have multiple Android Manifests you probably have to change the UnityPlayerActivity in the one closest to the root level. I struggled for some time in the demo project that has 2 Android Manifests and I only modified the other one which didn't change anything :man_facepalming:

**Comment by nicolasform** [comment] 2017-05-26 11:25
Yes, the one to change should be in Assets/Plugins/Android/AndroidManifest.xml for most projects.

**Comment by Hemaolle** [comment] 2017-05-30 06:23
All right I merged the fix now, I think it _should_ be ok also for earlier Unity versions.

**Closed by Hemaolle** 2017-05-30 06:23 UTC

**Comment by nicolasform** [comment] 2017-05-30 08:25
I think it should be ok for earlier Unity version too. If it is not, people just have to not change their manifest and the new UnityPlayerNotOnTopActivity class will never be called.

**Comment by ChisomoMbeza** [comment] 2017-09-06 12:33
Hello, I understand the adjustment to the android manifest but I do not understand the two java classes(UnityPlayerNotOnTop.java, UnityPlayerNotOnTopActivity.java), where do I create those?

**Comment by Hemaolle** [comment] 2017-09-06 13:12
Inside your Android plugin. But this shouldn't be necessary anymore, Unity returned to their previous implementation pretty quickly as far as I know.

**Comment by ChisomoMbeza** [comment] 2017-09-06 13:21
When you say they resolved it do you mean in unity 2017? because I am still on 5.6

**Comment by Hemaolle** [comment] 2017-09-06 13:24
According to this forum thread it was fixed in 5.6.1p4: https://forum.unity3d.com/threads/unity-5-6-0b3-android-plugin-cant-show-native-textview-or-layout.453193/

**Comment by nicolasform** [comment] 2017-09-06 13:31
I agree, this fix is not necessary anymore.

**Comment by ChisomoMbeza** [comment] 2017-09-06 13:32
I am updating to unity 2017 now, hopefully it is resolved because this is crucial to my project

**Comment by Hemaolle** [comment] 2017-09-06 13:33
As I said above 5.6.1p4 or higher should be enough.

**Comment by Hemaolle** [comment] 2017-09-06 13:34
Should work on 2017 also, of course.

**Comment by ChisomoMbeza** [comment] 2017-09-06 14:27
I have updated to 2017 and still having the same problem, when focusing on any field all fields become invisible, I know the text is there because my phone has a zoom feature when you hold on text and funny enough the text shows under the magnifying glass but not outside of it and when you get out of focus then all text shows again. 

It might be because of this, in the plugin guide it said change this line in the manifest :

<activity android:name="com.bkmin.android.UnityPlayerNotOnTopActivity"
   android:label="@string/app_name">

but when I do that my app builds but crashes on startup(which wasn't happening with Unity 5.6), so I kept it the original script: 

<activity android:name="com.unity3d.player.UnityPlayerNativeActivity"
                  android:label="@string/app_name">.

Please help, using the unity input fields breaks the most important feature of my app because of some sort of memory cache or something but when I use nativeEdit it works perfectly, except the input fields go invisible

**Comment by Hemaolle** [comment] 2017-09-06 14:30
The issue tracking tells that it should be fixed in 2017.2: https://issuetracker.unity3d.com/issues/regression-android-banner-ads-are-invisible-but-clickable. Which 2017 version did you update to?

**Comment by Hemaolle** [comment] 2017-09-06 14:32
And yeah, the manifest change should not be required anymore. I made a pull request to remove it from the readme a while ago: https://github.com/YousicianGit/UnityNativeEdit/pull/53 but it hasn't been reviewed yet.

**Comment by Hemaolle** [comment] 2017-09-06 14:33
Not sure if you are facing the same issue. As far as I can remember the fields weren't visible at any point with this bug.

**Comment by ChisomoMbeza** [comment] 2017-09-06 14:36
I am now currently using unity 2017.1 which was the latest available one on the site. I have followed the instructions to using the plugin probably 10 times today but maybe I am missing a step. Is there somewhere they are laid out differently?

**Comment by Hemaolle** [comment] 2017-09-06 14:39
Looks like 2017.2 is in beta: https://unity3d.com/unity/beta. Try that or 5.6.1p4 if you would rather have a stable version: https://unity3d.com/unity/qa/patch-releases/5.6.1p4.

**Comment by Hemaolle** [comment] 2017-09-06 14:41
As for updated instructions, you can check on my own fork: https://github.com/Hemaolle/UnityNativeEdit.

**Comment by ChisomoMbeza** [comment] 2017-09-06 14:46
I am downloading 5.6.1 and I am going to use your files and instructions to see what happens

**Comment by Hemaolle** [comment] 2017-09-06 14:48
And you took, the patch release p4 for 5.6.1, not the regular 5.6.1 I assume?

**Comment by ChisomoMbeza** [comment] 2017-09-06 14:49
I noticed the files come with their own Android manifest in plugins/android, I have my own in there already. Originally I replaced my old one with the one that came with UnityNativeEdit-master but that one is a lot shorter than my original one because I have other plugins. Do I have to replace my AndroidManifest with yours?

**Comment by ChisomoMbeza** [comment] 2017-09-06 14:49
Yes, I downloaded directly from the link you posted

**Comment by Hemaolle** [comment] 2017-09-06 14:51
I think I tried at some point without the custom manifest here and it worked just fine.

**Comment by Hemaolle** [comment] 2017-09-06 14:52
I think Unity also tries to merge multiple AndroidManifests to one in case you have multiple ones from different plugins in the future.

**Comment by ChisomoMbeza** [comment] 2017-09-06 15:10
Unfortunately I am still having the same problem.

here are screenshots

![screenshot_20170906-170609](https://user-images.githubusercontent.com/21374506/30119424-fdada396-9325-11e7-86cd-dd36daefa7f7.png)

_This is before I select a field_

![screenshot_20170906-170628](https://user-images.githubusercontent.com/21374506/30119440-0b60b94c-9326-11e7-8d58-ccb371b25eaa.png)
_When I focus on a field_

**Comment by Hemaolle** [comment] 2017-09-06 15:32
Did you try the UnityNativeEdit demo project?

I wonder if it's possible that you just have a white font there.

**Comment by ChisomoMbeza** [comment] 2017-09-06 16:01
I actually did and it has the same problem, if the input field is low enough for the keyboard to have to move it up then this happens otherwise it works just fine if the input field is high, sorry that's something I should have mentioned. I'm not I'm charge of the design so I have to find a work around. (try it in the demo scene if you'd like, move the input field low then build and you'll see this same thing happening.

I considered the font colour but my phone has a feature that allows you to zoom in on text and even though you still can't see it in unity the text actually shows under a magnifying glass on top of the finger you are holding down and it's black. And when you exit the input field the text shows

**Comment by Hemaolle** [comment] 2017-09-06 16:08
Oh yeah, I think I remember maybe seeing something like that indeed if the text field is located under the keyboard. At least I encountered a problem where the text was partially covered by the keyboard. There was some discussion earlier about adding a larger margin to the EditText on another issue: https://github.com/YousicianGit/UnityNativeEdit/issues/47. It's possible to add more padding in the Android code, but seems that there was perhaps a layout issue. You could ask on that issue if the developer got it solved in the end.

**Comment by Hemaolle** [comment] 2017-09-06 16:33
No problem :slightly_smiling_face: If you get it solved, please post here (or perhaps at issue https://github.com/YousicianGit/UnityNativeEdit/issues/47) so that others can benefit also :slightly_smiling_face: I might play around with it myself also, but not making promises :smile:

**Comment by ChisomoMbeza** [comment] 2017-09-06 16:35
Sure thing, the proton this the better. It's so much better to use the native keyboard because using the unity input fields as they are destroy the phone's ram and I'm working on an AR app so by the time you get to the AR part the camera is extremely slow, I actually tested it with native input and it was working perfectly except for the invisible text part

**Comment by Hemaolle** [comment] 2017-09-06 16:38
Interesting. If everything else fails, you could try to work around it by animating the text field position on Unity side or something like that, but of course it's not very nice.

**Comment by ChisomoMbeza** [comment] 2017-09-06 16:42
Yeah I actually had a script that moves fields above the keyboard on focus but that got completely overriden by NativeEdit script

**Comment by ChisomoMbeza** [comment] 2017-09-06 16:43
A lot of the work arounds are not great

**Comment by Hemaolle** [comment] 2017-09-06 16:47
Give this branch a go: https://github.com/Hemaolle/UnityNativeEdit/tree/padding-for-keyboard. It should add 20 px padding to the EditText, which should add some distance to the keyboard.

**Comment by Hemaolle** [comment] 2017-09-06 16:48
I can make it configurable from Unity if it helps.

**Comment by Hemaolle** [comment] 2017-09-06 16:51
Going to call it a day, I'll get back to you tommorw if you need more help.

**Comment by ChisomoMbeza** [comment] 2017-09-06 16:54
Thank you

**Comment by Hemaolle** [comment] 2017-09-07 05:20
@ChisomoMbeza, did the padding help?

**Comment by ChisomoMbeza** [comment] 2017-09-07 07:10
I am about to try it now, will keep you updated

**Comment by ChisomoMbeza** [comment] 2017-09-07 07:43
The invisibility is still occurring but I do see the effects of the padding, it in fact positions the input field perfectly as compared to before. 

Would you perhaps know how to activate the native input field that appears above the keyboard, that way at least the user can see what they are entering

**Comment by Hemaolle** [comment] 2017-09-07 07:48
I don't remember by heart how to display the extra textbox, should be easy to find with some Googling, though.

I don't know what would be the difference compared to normal Unity input field then though, since getting rid of that extra text box is the reason to use this plugin after all :smile:

**Comment by Hemaolle** [comment] 2017-09-07 07:49
The text box probably is something you can configure with the imeOptions or similar.

**Comment by ChisomoMbeza** [comment] 2017-09-07 07:51
Here is what happens:

![20170907_094814](https://user-images.githubusercontent.com/21374506/30151973-e15a6a8a-93b1-11e7-84e9-1e83007887e8.jpg)
![20170907_094828](https://user-images.githubusercontent.com/21374506/30151979-e755878a-93b1-11e7-9586-9bb28eaa8be5.jpg)


The fact that is is showing text under the magnifying glass means that the text is there and it is black, it's just not visible

**Comment by ChisomoMbeza** [comment] 2017-09-07 07:53
Actually that is not the reason I got the native edit, I got the native edit because the unity input wastes ram and that cache in ram is never cleared  for some reason so by the time I get to my scene with an AR camera it is really slow, the native input gets rid of this problem

**Comment by Hemaolle** [comment] 2017-09-07 07:53
Yeah, that is weird. I didn't have the same problem on my device even if the text was partially covered by the keyboard (before adding the padding) it was still visible just fine).

**Comment by ChisomoMbeza** [comment] 2017-09-07 07:56
It seems to be a well known problem that unity refuses to fix, for a while I thought my AR scenes were just not optimized well enough and I spent 3 days doing whatever I could to save memory and the scene was still slow until  I tried the native input then the AR camera is just as fast as the native camera app of the phone

**Comment by Hemaolle** [comment] 2017-09-07 08:00
☹

But yeah, I would perhaps try to find out if the disappearing text is some Android issue. Found something like this on a quick googling: https://stackoverflow.com/questions/19897422/keyboard-hiding-edittext-when-androidwindowtranslucentstatus-true

**Comment by Hemaolle** [comment] 2017-09-07 08:01
In any case I don't think it's the issue that required the UnityPlayerNotOnTop stuff etc., with that bug the text was never visible, whether it was under the keyboard or not, focused or not.

**Comment by ChisomoMbeza** [comment] 2017-09-07 08:04
It works perfectly if the text was high enough to no have to be moved up by the keyboard:

![20170907_100149](https://user-images.githubusercontent.com/21374506/30152562-c66b1ab0-93b3-11e7-8732-3ac43a9ae67d.jpg)

![20170907_100158](https://user-images.githubusercontent.com/21374506/30152576-cf10f3ba-93b3-11e7-833b-4dc344ff879c.jpg)

**Comment by Hemaolle** [comment] 2017-09-07 08:06
Yeah

**Comment by Hemaolle** [comment] 2017-09-11 05:46
@ChisomoMbeza, how is it going? Were you able to find a solution?

**Comment by ChisomoMbeza** [comment] 2017-09-11 07:00
Hello, I am well and hope you are too. No I was not able to find a solution yet, your side?

**Comment by Hemaolle** [comment] 2017-09-11 09:28
No, and I can't really look into it since it doesn't seem to happen on my device.

**Comment by ChisomoMbeza** [comment] 2017-09-11 09:30
Even when the input field was low enough that the keyboard had to move it up?

**Comment by Hemaolle** [comment] 2017-09-11 09:31
Nope
>Yeah, that is weird. I didn't have the same problem on my device even if the text was partially covered by the keyboard (before adding the padding) it was still visible just fine).

**Comment by ChisomoMbeza** [comment] 2017-09-11 09:34
Then it must be the way I implemented it because I have tested it out on different devices. I do not who where I went wrong though, I followed your instructions word by word. But then again I tested out the demo scene and it also had this problem

**Comment by Hemaolle** [comment] 2017-09-11 09:40
I was checking the demo scene also, not seeing it (Moto G4, Android 7.0).

**Comment by Hemaolle** [comment] 2017-09-11 09:41
Maybe I have a rare device where it works :smile:

**Comment by ChisomoMbeza** [comment] 2017-09-11 09:41
I've tested it on Samsung S7 and Sony XZ with the latest Android software

**Comment by ChisomoMbeza** [comment] 2017-09-11 09:41
Could you please send screenshots if possible

**Comment by Hemaolle** [comment] 2017-09-11 09:47
![image](https://user-images.githubusercontent.com/2861820/30268701-398951ae-96ef-11e7-8701-8c34bfd0aaaf.png)
There you go. I just added another single line input field to the bottom of the demo scene to make it covered by the keyboard and this is the version with more padding, but you said that it didn't make difference anyway.

**Comment by ChisomoMbeza** [comment] 2017-09-11 09:49
is it possible to send me the project with that working demo scene?

**Comment by Hemaolle** [comment] 2017-09-11 09:56
There you go: https://github.com/Hemaolle/UnityNativeEdit/tree/sample-for-chisomo

**Comment by ChisomoMbeza** [comment] 2017-09-11 09:57
Thank you, going to test it out now

**Comment by ChisomoMbeza** [comment] 2017-09-11 10:06
It works!!!!! Now to try to get it to work like this on my project

**Comment by ChisomoMbeza** [comment] 2017-09-11 10:48
It seems to work in the demo scene but not on my scene. I just noticed something in your instructions that I have not implemented:

NativeEditBox will work with delegate defined in your Unity UI InputField, On Value Change and End Edit
It's open source and free to use/redistribute!
Please refer to demo Unity project.

Please explain this to me

**Comment by ChisomoMbeza** [comment] 2017-09-11 10:51
I made a prefab of the working input box from the scene and put it in my scene and it had the same problem. There has to be something I am missing

**Comment by Hemaolle** [comment] 2017-09-11 11:05
>NativeEditBox will work with delegate defined in your Unity UI InputField, On Value Change and End Edit

You use the NativeEditBox by adding the MonoBehaviour to a Unity UI InputField. This quote means that if you hook up methods to `On Value Changed` and `On End Edit` events on the Unity InputField they will be called also when the `NativeEditBox` takes over on a mobile device.

>I made a prefab of the working input box from the scene and put it in my scene and it had the same problem. There has to be something I am missing

Did you do this part from the Readme:

>Make empty Gameobject and attach PluginMsgHandler to your new GameObject

**Comment by Hemaolle** [comment] 2017-09-11 11:06
Of course it could be possible that one of your other plugins has bad interaction with this plugin.

**Comment by ChisomoMbeza** [comment] 2017-09-11 11:08
Yes I did:

![1](https://user-images.githubusercontent.com/21374506/30271877-3c0b938a-96f2-11e7-9ce5-a3ed74d5e183.PNG)


![2](https://user-images.githubusercontent.com/21374506/30271882-4244bd76-96f2-11e7-8dca-f75ce4b5799b.PNG)

**Comment by ChisomoMbeza** [comment] 2017-09-11 11:08
Perhaps but the demo scene is in the same project, would it not cause conflict there too?

**Comment by Hemaolle** [comment] 2017-09-11 11:10
Perhaps not if the other plugins are not used in that scene.

**Comment by ChisomoMbeza** [comment] 2017-09-11 11:19
Perhaps, otherwise does the setup on my side seem accurate? Based on the screenshots, should it be working?

**Comment by Hemaolle** [comment] 2017-09-11 12:30
Yeah, can't see anything wrong there. Since you have a working scene now, I'd just either disable the stuff on your broken scene 1 by 1 until it starts working or add the safe stuff again to the working scene and see at which point it will break.

Might be hard to fix the problem still though if you need all the other plugins too.

**Comment by ChisomoMbeza** [comment] 2017-09-11 12:32
That is actually what I am doing now. I took my one scene and put it in the demo scene then disabled it and tested (still working), now I'm enabling objects one by one

**Comment by ChisomoMbeza** [comment] 2017-09-11 13:12
Okay I have broken and reconstructed this demo scene a dozen times now trying to combine it with my scene and I can confirm one this, the input doesn't work properly if you change anything. even just disabling the buttons and other input fields in the scene  (which aren't supposed to be related to it in any way) breaks it

**Comment by Hemaolle** [comment] 2017-09-11 19:00
Seems correct, I was able to reproduce on my end by disabling the other native input field on the scene.

I was able to get the text visible by enabling the `Update Rect Every Frame` flag on the `NativeEditBox` inspector. I'm not 100 % what causes the bug, but I suspect that the native `EditText` is somehow pushed outside its limits by the keyboard or something like that and this method updates the position on every frame, which seems to fix the issue. It might be a bit heavy to do this, and a better, more lightweight fix might be possible somehow. That flag was created for a situation where an input field is moving on the screen during some animations.

I updated my sample for you with a working demo scene:

https://github.com/Hemaolle/UnityNativeEdit/tree/sample-for-chisomo

**Comment by ChisomoMbeza** [comment] 2017-09-12 07:19
Thank yo, I will give this fix sometime today

**Comment by Hemaolle** [comment] 2017-09-18 12:38
@ChisomoMbeza, was your problem solved?

**Comment by ChisomoMbeza** [comment] 2017-09-19 08:27
I could not solve it with this plugin so ended up using another on because I was pressed for time due to this being a project for a client

**Comment by Hemaolle** [comment] 2017-09-19 08:30
Too bad :slightly_frowning_face:

I'm curious, which plugin did you end up using? When I was picking up this plugin I had hard time finding good alternatives.

**Comment by ChisomoMbeza** [comment] 2017-09-19 08:34
Yeah, thank you so much for the assistance, you really went out of your way to help which is much appreciated.

I ended up using Advanced Input Field

**Comment by Hemaolle** [comment] 2017-09-19 08:40
No problem.

Advanced Input Field looks promising, it's probably going to save you a lot of trouble :)

**Comment by ChisomoMbeza** [comment] 2017-09-19 13:44
It solved the biggest problem I was having so yeah it did the job

**Comment by Hemaolle** [comment] 2017-09-19 14:23
I'm kind of curious, did the last solution not work for you at all, or was it too heavy to run?

**Comment by ChisomoMbeza** [comment] 2017-09-19 14:27
Your solution actually worked perfectly save for the invisible text

**Comment by Hemaolle** [comment] 2017-09-19 14:34
This thing I posted last a week ago was supposed to fix the invisibility, but I guess it didn't do that for you then?
>Seems correct, I was able to reproduce on my end by disabling the other native input field on the scene.
>
>I was able to get the text visible by enabling the Update Rect Every Frame flag on the NativeEditBox inspector. I'm not 100 % what causes the bug, but I suspect that the native EditText is somehow pushed outside its limits by the keyboard or something like that and this method updates the position on every frame, which seems to fix the issue. It might be a bit heavy to do this, and a better, more lightweight fix might be possible somehow. That flag was created for a situation where an input field is moving on the screen during some animations.
>
>I updated my sample for you with a working demo scene:
>
>https://github.com/Hemaolle/UnityNativeEdit/tree/sample-for-chisomo

**Comment by ChisomoMbeza** [comment] 2017-09-19 14:37
Oh yes I had tried that and it did not work
